server:
  port: 8118
branding:
  custom-footer: |
    <p>from <a href="https://hndsinh.site">hndsinh.site</a> with love ♥</p>
  logo-text: hndsinh

theme:
  background-color: 50 1 6
  primary-color: 24 97 58
  negative-color: 209 88 54
pages:
  - name: Home
    width: slim
    center-vertically: true
    columns:
      - size: full
        widgets:
          - type: search
            autofocus: true
            new-tab: true
            search-engine: google
            bangs:
              - title: YouTube
                shortcut: "!yt"
                url: https://www.youtube.com/results?search_query={QUERY}

          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Jellyfin
                url: https://yourdomain.com/
                icon: si:jellyfin
              - title: Gitea
                url: https://yourdomain.com/
                icon: si:gitea
              - title: qBittorrent # only for Linux ISOs, of course
                url: https://yourdomain.com/
                icon: si:qbittorrent
              - title: Immich
                url: https://yourdomain.com/
                icon: si:immich
              - title: AdGuard Home
                url: https://yourdomain.com/
                icon: si:adguard
              - title: Vaultwarden
                url: https://yourdomain.com/
                icon: si:vaultwarden

          - type: bookmarks
            groups:
              - title: General
                links:
                  - title: Gmail
                    url: https://mail.google.com/mail/u/0/
                  - title: Amazon
                    url: https://www.amazon.com/
                  - title: Github
                    url: https://github.com/
              - title: Entertainment
                links:
                  - title: YouTube
                    url: https://www.youtube.com/
                  - title: Prime Video
                    url: https://www.primevideo.com/
                  - title: Disney+
                    url: https://www.disneyplus.com/
              - title: Social
                links:
                  - title: Reddit
                    url: https://www.reddit.com/
                  - title: Twitter
                    url: https://twitter.com/
                  - title: Instagram
                    url: https://www.instagram.com/  
  - name: News
    # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
    # hide-desktop-navigation: true
    columns:
      - size: small
        widgets:
          - type: calendar
            first-day-of-week: monday

          - type: rss
            limit: 10
            collapse-after: 3
            cache: 12h
            feeds:
              - url: https://selfh.st/rss/
                title: selfh.st
                limit: 4
              - url: https://ciechanow.ski/atom.xml
              - url: https://www.joshwcomeau.com/rss.xml
                title: Josh Comeau
              - url: https://samwho.dev/rss.xml
              - url: https://ishadeed.com/feed.xml
                title: Ahmad Shadeed

          - type: twitch-channels
            channels:
              - theprimeagen
              - j_blow
              - piratesoftware
              - cohhcarnage
              - christitustech
              - EJ_SA

      - size: full
        widgets:
          - type: group
            widgets:
              - type: hacker-news
              - type: lobsters

          - type: videos
            channels:
              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCsBjURrPoezykLs9EqgamOA # Fireship
              - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
              - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

          - type: group
            widgets:
              - type: reddit
                subreddit: technology
                show-thumbnails: true
              - type: reddit
                subreddit: selfhosted
                show-thumbnails: true

      - size: small
        widgets:
          - type: weather
            location: Ho Chi Minh City
            units: metric # alternatively "imperial"
            hour-format: 24h # alternatively "24h"
            # Optionally hide the location from being displayed in the widget
            # hide-location: true
          - type: clock
            hour-format: 24h
            timezones:
              - timezone: Asia/Bangkok
                label: Viet Nam
              - timezone: Europe/Paris
                label: Paris
              - timezone: America/New_York
                label: New York
          - type: markets
            markets:
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: ETH-USD
                name: Ethereum
              - symbol: LINK-USD
                name: Link
              - symbol: NEAR-USD
                name: Near
              - symbol: TON-USD
                name: Ton
